#! /bin/sh

for file in `find testfiles -type f -name '*.c'`
do
    echo "Parsing $file"
    python3 c2llvm.py $file
    echo "Generated LLVM IR $file"
done
echo "Generating images from dotfiles"
for file in `find testfiles -type f -name '*.dot'`
do
    dot -Tpng -o `echo $file | sed s/\.dot/\.png/` $file
done